spring.application.name=user-api
internal.chat.client-id=${MESSAGE_CLIENT_ID}
internal.chat.client-secret=${MESSAGE_CLIENT_SECRET}
internal.oauth.issuer=${INTERNAL_OAUTH_ISSUER}
jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION}
jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION}
