spring.application.name=chat-message
internal.oauth.token-uri=${INTERNAL_OAUTH_TOKEN_URI}
internal.oauth.client-id=${MESSAGE_CLIENT_ID}
internal.oauth.client-secret=${MESSAGE_CLIENT_SECRET}
internal.chat-api.base-url=${CHAT_API_BASE_URL}

