spring.application.name=chat-message
messaging.redis.topic-prefix=${REDIS_TOPIC_PREFIX}
spring.data.redis.timeout=5s
internal.oauth.token-uri=${INTERNAL_OAUTH_TOKEN_URI}
internal.oauth.client-id=${MESSAGE_CLIENT_ID}
internal.oauth.client-secret=${MESSAGE_CLIENT_SECRET}
internal.chat-api.base-url=${CHAT_API_BASE_URL}

