# h2 settings
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# datasource & h2 settings
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:file:./data/discord-be
#spring.datasource.username=sa

# Swagger
springdoc.swagger-ui.path=/api-doc

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=discord
spring.data.mongodb.replica-set-name=rs0
spring.data.mongodb.auto-index-creation=true

# Server
server.port=8081
server.servlet.session.cookie.domain=msdiscord.site

# Security
jwk-set-uri=http://localhost:8080/oauth2/jwks